apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: odiglet
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odiglet
subjects:
- kind: ServiceAccount
  name: odiglet
  namespace: default
