apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: odigos-instrumentor
spec:
  ports:
  - name: webhook-server
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: odigos-instrumentor
status:
  loadBalancer: {}
