apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: odigos-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odigos-ui
subjects:
- kind: ServiceAccount
  name: odigos-ui
  namespace: default
