apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: odigos-ui
  name: ui
spec:
  ports:
  - name: ui
    port: 3000
    targetPort: 0
  - name: otlp
    port: 4317
    targetPort: 0
  selector:
    app: odigos-ui
status:
  loadBalancer: {}
